In [26]:
# Importing library
import numpy as np

<hr>

#### Numpy basics

In [27]:
y=np.array([1,2,3]) # creating the 1D array
y[0] # 0-indexed

1

In [28]:
y.shape # (rows,columns)

(3,)

In [29]:
y.ndim # (dimension)

1

In [30]:
y.itemsize # size of element (integer: 4)

4

In [31]:
np.zeros((1,2)) # parameters: rows and columns

array([[0., 0.]])

In [32]:
np.ones(([3,4]))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<hr>

### Numpy dtypes

In [33]:
y = np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
y

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [34]:
y.itemsize # float: 8

8

In [35]:
y= np.array([[1,2],[3,4],[5,6]],dtype=np.complex_)
y

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [36]:
y.itemsize # complex: 16

16

<hr>

### Numpy string functions

In [37]:
print(np.char.add(['hello','hi'],["abc","xyz"]))

['helloabc' 'hixyz']


In [38]:
print(np.char.multiply(["hello","hi"],3))

['hellohellohello' 'hihihi']


In [39]:
print(np.char.count(["helloo","hih","hhad","abc"],'h',0,2)) # gives count of a substring in the array of strings
# 0,3 indicates start and end position to search in each string in the array

[1 1 2 0]


In [40]:
print(np.char.center("hello",10,fillchar="-"))

--hello---


In [41]:
print(np.char.capitalize(["hello hi","hi"])) # first letter of each string is converted to uppercase

['Hello hi' 'Hi']


In [42]:
print(np.char.title(["hello hi","hi"])) # converts first letter in each word of the string in the array to uppercase

['Hello Hi' 'Hi']


In [43]:
print(np.char.compare_chararrays("hi ","hi",cmp="==",rstrip=False))

False


In [44]:
print(np.char.upper("hello"))
print(np.char.lower("HEllo"))

HELLO
hello


In [45]:
print(np.char.split("hello! how are you dear",maxsplit=2))

['hello!', 'how', 'are you dear']


In [46]:
print(np.char.split("hello!\nhow are you"))

['hello!', 'how', 'are', 'you']


In [47]:
print(np.char.strip(["admin","anaia","nia"],'a')) # strips off starting and ending 'a'

['dmin' 'nai' 'ni']


In [48]:
print(np.char.join([":","-"],["dmy"]))

['d:m:y' 'd-m-y']


In [49]:
print(np.char.replace("he is good dancer","is","was"))

he was good dancer


<hr>

### Difference between Python lists and numpy arrays

In [50]:
import time
import sys

Numpy consumes less memory 

In [51]:
r=range(1000) 
print("memory size: ",sys.getsizeof(1)*len(r))
n=np.arange(1000)
print("memory size: ",n.itemsize*n.size)

memory size:  28000
memory size:  4000


Numpy is fast - Less Computational time

In [52]:
size=100000
start=time.time()
a=range(size)
b=range(size)
result=[(x+y) for x,y in zip(a,b)]
print("Python list took: ",(time.time()-start)*1000)

Python list took:  15.998125076293945


In [53]:
size=100000
start=time.time()
a=np.arange(size)
b=np.arange(size)
result=a+b
print("Numpy took: ",(time.time()-start)*1000)

Numpy took:  1.9974708557128906


<hr>

### Array Manipulation

In [54]:
arr=np.array([0,1,2,3,4,5,6,7,8,9,10,11])
arr.shape

(12,)

In [55]:
arr1=np.arange(12).reshape(4,3)
print("(4,3)\n",arr.reshape(4,3))
print("(2,6)\n",arr.reshape(2,6))
# (m,n) - m*n total number of elements

(4,3)
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(2,6)
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [56]:
print(arr1.flatten())
print(arr1.flatten(order="F"))
# order: F-column major C-row major(default) A:

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  3  6  9  1  4  7 10  2  5  8 11]


In [57]:
print(arr)
print(arr.reshape(2,2,3))
np.transpose(arr.reshape(2,2,3))

# Transpose of (2,3,4) is (4,3,2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


array([[[ 0,  6],
        [ 3,  9]],

       [[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]]])

In [58]:
# difference between resize and reshape
sample=np.array([[1,2,3],[4,5,6]])
sample2=np.resize(sample,(3,8))
# sample3=np.reshape(sample,(3,8)) error
print(sample)
print(sample2)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5 6]]


In [59]:
s1=np.array([['a','b'],['c','d']])
print(s1,end="\n\n")
print(np.transpose(s1),end="\n\n")

[['a' 'b']
 ['c' 'd']]

[['a' 'c']
 ['b' 'd']]



In [60]:
s2=np.array([[['a','b'],['c','d']],[['e','f'],['g','h']]])
print(s2,end="\n------------------\n")
print(np.transpose(s2),end="\n\n")

[[['a' 'b']
  ['c' 'd']]

 [['e' 'f']
  ['g' 'h']]]
------------------
[[['a' 'e']
  ['c' 'g']]

 [['b' 'f']
  ['d' 'h']]]



In [85]:
np.rollaxis(s2,2,1)

array([[['a', 'c'],
        ['b', 'd']],

       [['e', 'g'],
        ['f', 'h']]], dtype='<U1')

In [89]:
a=np.ones((3,4,5,6))
print(np.rollaxis(a,3,1).shape)
print(np.rollaxis(a,2).shape)
print(np.rollaxis(a,1,4).shape)

(3, 6, 4, 5)
(5, 3, 4, 6)
(3, 5, 6, 4)


<hr>

### Numpy arithematic operations

In [62]:
x1=np.array([[1,2,3],[2,4,5]])
x2=np.array([3,7,2])

# Element wise operations
print(np.add(x1,x2))
print(np.subtract(x1,x2))
print(np.multiply(x1,x2))
print(np.divide(x1,x2))

[[ 4  9  5]
 [ 5 11  7]]
[[-2 -5  1]
 [-1 -3  3]]
[[ 3 14  6]
 [ 6 28 10]]
[[0.33333333 0.28571429 1.5       ]
 [0.66666667 0.57142857 2.5       ]]


<hr>

### Slicing

In [63]:
sli=np.arange(20)
sli

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
print(sli[4:])
print(sli[:4])
print(sli[2:5])
print(sli[:-3])
print(sli[-2:])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3]
[2 3 4]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[18 19]


In [65]:
print(sli[slice(2,10,3)]) # start end step-difference
# or sli[2:10:3]

[2 5 8]


<hr>

### Iterating array

In [66]:
ita=np.arange(0,45,5)
ita=ita.reshape(3,3)
ita

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [67]:
# for i in ita:
#     for j in i:
#         print(j)

for x in np.nditer(ita):
    print(x)

0
5
10
15
20
25
30
35
40


In [68]:
for x in np.nditer(ita,order="C"): # Row-major
    print(x)

for x in np.nditer(ita,order="F"): # Column-major
    print(x)

0
5
10
15
20
25
30
35
40
0
15
30
5
20
35
10
25
40


<hr>

### Joining array

In [69]:
f=np.array([[1,2],[3,4]])
print("first array:\n",f)
s=np.array([[5,6],[7,8]])
print("second array:\n",s)

first array:
 [[1 2]
 [3 4]]
second array:
 [[5 6]
 [7 8]]


In [70]:
print("concatenated array:\n",np.concatenate((f,s))) # along axis 0
print("shape: ",np.concatenate((f,s)).shape)

concatenated array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
shape:  (4, 2)


In [71]:
print("concatenated array:\n",np.concatenate((f,s),axis=1)) # along axis 1
print("shape: ",np.concatenate((f,s),axis=1).shape)

concatenated array:
 [[1 2 5 6]
 [3 4 7 8]]
shape:  (2, 4)


<hr>

### Splitting the array

In [72]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.split(a,5) # 5: number of splits (each split should have equal number of elements)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [74]:
np.split(a,[2,5])
# split 1: a[:2]    split 2: a[2:5]     split 3: a[5:]

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

<hr>

In [75]:
a=np.linspace(1,3,10) # starting number: 1      ending number: 3
# even gha split chestundi 10 numbers 
a

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [94]:
a=np.array([[1,2,3],[3,4,5]])
print(a.sum(axis=0))
print(a.sum(axis=1))

[4 6 8]
[ 6 12]


In [95]:
print(np.sqrt(a),end="\n\n")
print(np.std(a),end="\n\n")
print(np.log10(a),end="\n\n")

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]

1.2909944487358056

[[0.         0.30103    0.47712125]
 [0.47712125 0.60205999 0.69897   ]]



In [97]:
print(a.ravel(order='F'))
a

[1 3 2 4 3 5]


array([[1, 2, 3],
       [3, 4, 5]])

<hr>