In [41]:
import tensorflow as tf

In [42]:
print(('Your tensorflow version: {0}').format(tf.__version__))

Your tensorflow version: 2.10.0


<hr>

In [43]:
z=tf.constant(5.2,name="x",dtype=tf.float32)
z

<tf.Tensor: shape=(), dtype=float32, numpy=5.2>

In [44]:
# Variables in Tensorflow are in-memory buffers that store tensors
v=tf.Variable(tf.ones([3,3],dtype=tf.float32))
v

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [45]:
c=tf.constant(tf.zeros([2,3],dtype=tf.float32))
c

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [46]:
c_reshaped=tf.reshape(tensor=c,shape=[3,2])
c_reshaped

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [47]:
c_as_int=tf.cast(c,tf.int32) # floor value of integer is taken
c_as_int

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [48]:
c_transpose = tf.transpose(c)
c_transpose

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [67]:
rows,columns = c.shape
print('rows: ',rows,'columns: ',columns)
c_identity = tf.eye(num_rows=rows,num_columns=columns,dtype=tf.int32)
c_identity

rows:  2 columns:  3


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0]])>

<hr>

In [56]:
x=tf.Variable([[1,2,3],[4,5,6],[1,2,4]],dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 4.]], dtype=float32)>

In [57]:
y=tf.constant([[1,2,1],[1,5,4],[3,2,4]],dtype=tf.float32)
y

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 1.],
       [1., 5., 4.],
       [3., 2., 4.]], dtype=float32)>

In [58]:
xy_concatenated = tf.concat(values=[x,y],axis=0)
xy_concatenated

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 4.],
       [1., 2., 1.],
       [1., 5., 4.],
       [3., 2., 4.]], dtype=float32)>

In [59]:
xy_mat_multiplication = tf.matmul(x,y) # Matrix multiplication
xy_mat_multiplication 

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[12., 18., 21.],
       [27., 45., 48.],
       [15., 20., 25.]], dtype=float32)>

In [60]:
xy_element_multiplication = tf.multiply(x,y)
xy_element_multiplication

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.,  4.,  3.],
       [ 4., 25., 24.],
       [ 3.,  4., 16.]], dtype=float32)>

<hr>

In [ ]:
# Session in Tensorflow is used to run a computational graph to evaluate the nodes
x=tf.constant(10.0,name="x",dtype=tf.float32)
y=tf.constant(20.0,name="y",dtype=tf.float32)
z=tf.Variable(tf.add(x,y))

# init=tf.global_variables_initializer()
# with tf.Session() as session:
#     session.run(init)
#     print(session.run(y))

<hr>